### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by sjaeckel**
This PR adds a new `/strophe` command that allows the user to modify strophe-internal settings.

Currently there's support for manipulation of the Stream-Management feature and the verbosity of Debug output.

This also 

* modifies the log command to be less strict regarding capitalization when accepting user input.
* fixes some memory leaks
* introduces the usage of auto-free'ing of strings via a `auto_char` resp. `auto_gchar` macro
* improves the `command_defs[]` struct
* adds a `now` option to the reconnect command
* changes the API of `account_new()` to do less memory allocations

### CODE REVIEW

File: src/command/cmd_funcs.c [hunk 1]
```diff
@@ -8580,31 +8579,24 @@ _update_presence(const resource_presence_t resource_presence,
...
 {
     if (arg == NULL) {
         cons_bad_cmd_usage(command);
-    } else if (strcmp(arg, "on") == 0) {
-        GString* enabled = g_string_new(display);
-        g_string_append(enabled, " enabled.");
-
-        cons_show(enabled->str);
+        return FALSE;
+    } else if (g_strcasecmp(arg, "on") == 0) {
```
Comment (jubalh) [inline src/command/cmd_funcs.c:8589]: Usually we use case sensitive comparison. This one is fine for me as well. Just thinking whether it might be strange if it works in some cases case sensitive and in others not.

File: src/ui/console.c [hunk 2]
```diff
@@ -2311,6 +2311,7 @@ cons_show_connection_prefs(void)
     cons_autoping_setting();
     cons_autoconnect_setting();
     cons_rooms_cache_setting();
+    cons_strophe_setting();
```
Comment (jubalh) [inline src/ui/console.c:2314]: Hehe Just wanted to write "I think this should go into `cons_show_connection_prefs()` or `cons_prefs()`" but after a refresh it was done already :)

**Review by jubalh — COMMENTED** [review]
Nice feature! And some good catches in your changes as well! Thanks!
Only thing I see is that autocompletion for `/stophe` command is missing.

File: src/command/cmd_funcs.c (hunk 1 above)
Comment (sjaeckel) [reply src/command/cmd_funcs.c:8591]: > Usually we use case sensitive comparison

why? I can understand case sensitivity for some things, but ON vs. On vs. on vs. oN shouldn't make a difference ... this is als true for other settings, but that's the first one where I've changed it.

IMO Postel's law is very important when it comes to usability of software.

Comment (jubalh) [reply src/command/cmd_funcs.c:8591]: I'm not saying we SHOULD use case sensitive comparison.
I'm only saying that so far we do. And I would find it weird to now change this in only *one* occasion :)
I think it should be uniform.

From the top of my head I don't remember whether it actually is important/needed that we do that. So we could change it everywhere to be case insensitive. But I don't actually see any advantage it that. It might be that we miss something where it would make sense to be case sensitive. And then we have to change everything back. Plus it would just create work.

Those to reasons are why I think it it should be changed. The main reason is to be uniform though.

And I also see:
```
g_strcasecmp has been deprecated since version 2.2 and should not be used in newly-written code.
See g_strncasecmp() for a discussion of why this function is deprecated and how to replace it.
```

```
The problem with g_strncasecmp() is that it does the comparison by calling toupper()/tolower(). These functions are locale-specific and operate on single bytes...
````

File: src/command/cmd_funcs.c [hunk 3]
```diff
@@ -9856,6 +9851,41 @@ cmd_mood(ProfWin* window, const char* const command, gchar** args)
     return TRUE;
 }
 
+gboolean
+cmd_strophe(ProfWin* window, const char* const command, gchar** args)
+{
+    if (g_strcasecmp(args[0], "verbosity") == 0) {
```
Comment (jubalh) [inline src/command/cmd_funcs.c:9857]: same as above (strcasecmp)

**Comment by sjaeckel** [comment]
@thexhr as you're on OpenBSD, could you please check whether this branch is OK for you? I've introduced usage of `__attribute__((__cleanup__( )))` and I'm not 100% sure whether that's available for you!? It should be since it's a compiler extension, but I'd prefer to have it verified before merging and it breaks... Thanks!

**Comment by thexhr** [comment]
@sjaeckel The branch builds fine on OpenBSD 7.2-current (amd64, clang 13.0.0) and I spot no regression so far.

**Comment by jubalh** [comment]
`src/xmpp/message.c:532:19: error: unused variable 'jidp' [-Werror,-Wunused-variable]`

**Comment by sjaeckel** [comment]
> `src/xmpp/message.c:532:19: error: unused variable 'jidp' [-Werror,-Wunused-variable]`

awesome! by removing/replacing code we find out that even more code can be removed ;)

**Review by jubalh — APPROVED** [review]

**Comment by jubalh** [comment]
Looks great! Lots of improvements! Thanks!
