### ISSUE TITLE
Can't compile with GLib version on Ubuntu 10.04

### ISSUE THREAD

**Issue by boothj5** [profanity-im/profanity#20]
Error:

prof_autocomplete.c: In function ‘p_autocomplete_clear’:
prof_autocomplete.c:51: error: implicit declaration of function ‘g_slist_free_full’

GLib version:

2.24.1-0ubuntu1
