### ISSUE TITLE
Python 3.11 error: 'PyFrameObject' {aka 'struct _frame'} has no member named 'f_code'

### ISSUE THREAD

**Issue by fantomfp** [profanity-im/profanity#1634]
profanity fails to build with Python 3.11.0a4.

```
src/plugins/python_api.c: In function 'python_api_register_command':
src/plugins/python_api.c:199:31: warning: the comparison will always evaluate
as 'true' for the address of 'c_arguments' will never be NULL [-Waddress]
  199 |         while (c_arguments[i] != NULL && c_arguments[i][0] != NULL) {
      |                               ^~                                                                                                                                                                                                       
src/plugins/python_api.c:161:15: note: 'c_arguments' declared here
  161 |         char* c_arguments[args_len == 0 ? 0 : args_len + 1][2];
      |               ^~~~~~~~~~~                                                                                                                                                                                                              
src/plugins/python_api.c: In function '_python_plugin_name':
src/plugins/python_api.c:1622:32: error: 'PyThreadState' {aka 'struct _ts'} has
no member named 'frame'; did you mean 'cframe'?
 1622 |     PyFrameObject* frame = ts->frame;
      |                                ^~~~~                                                                                                                                                                                                   
      |                                cframe                                                                                                                                                                                                  
src/plugins/python_api.c:1623:59: error: 'PyFrameObject' {aka 'struct _frame'}
has no member named 'f_code'
 1623 |     char* filename =
python_str_or_unicode_to_string(frame->f_code->co_filename);
      |                                                                                                                                                                                                                                        

Changes of the PyFrameObject structure members:
    f_code: removed, use PyFrame_GetCode() instead. Warning: the function
returns a strong reference, need to call Py_DECREF().
    f_back: changed, use PyFrame_GetBack().
    f_builtins: removed, use PyObject_GetAttrString(frame, "f_builtins").
    f_globals: removed, use PyObject_GetAttrString(frame, "f_globals").
    f_locals: removed, use PyObject_GetAttrString(frame, "f_locals").
    f_lasti: removed, use PyObject_GetAttrString(frame, "f_lasti").
    f_valuesstack: removed.
    f_stackdepth: removed.
    f_gen: removed.
    f_iblock: removed.
    f_state: removed.
    f_blockstack: removed.
    f_localsplus: removed.
```

The Python frame object is now created lazily. A side effect is that the f_back
member must not be accessed directly, since its value is now also computed
lazily. The PyFrame_GetBack() function must be called instead.

Code defining PyFrame_GetCode() on Python 3.8 and older:

https://docs.python.org/3.11/whatsnew/3.11.html

Python 3.11 is planned to be included in Fedora 37. To make that update
smoother, we're building Fedora packages with all pre-releases of Python 3.11.

If you need more infos, tell me :-)

The "make" command-line was:
```
/usr/bin/make -O -j2 V=1 VERBOSE=1
```

**Comment by fantomfp** [comment]
The gcc command-line which produced this error was:
```
gcc -DHAVE_CONFIG_H -I. -I./src  -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -pthread  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/libmount -I/usr/include/blkid -pthread   -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/sysprof-4 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -pthread  -I/usr/include/python3.11   -DTHEMES_PATH="\"/usr/share/profanity/themes\"" -DICONS_PATH="\"/usr/share/profanity/icons\""  -Wall -Wno-deprecated-declarations -std=gnu99 -I./src -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -pthread   -c -o src/plugins/python_api.o src/plugins/python_api.c
```

**Comment by jubalh** [comment]
@fantomfp if you want to have this in 0.12.0 then now would be the time :) Otherwise I'll move this to 0.13.

**Comment by fantomfp** [comment]
Sorry I can't fix it, I don't handle C++.

**Comment by jubalh** [comment]
C++?

**Comment by fantomfp** [comment]
> C++?
The code in the file "src/plugins/python_api.c"

**Comment by jubalh** [comment]
Not sure where you see C++ code.

Just for future reference why the assignment was done: was discussed in MUC.
